project_id = "im-okay"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = true
port = 54323

[local_smtp]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://127.0.0.1:8081"
additional_redirect_urls = [
  "imokay://**",
  "http://127.0.0.1:8081/**",
  "http://localhost:8081/**",
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false
max_frequency = "1s"
otp_length = 6
otp_expiry = 3600

[edge_runtime]
enabled = true
policy = "oneshot"
inspector_port = 8083

[analytics]
enabled = false

[functions.api]
enabled = true
verify_jwt = true

[functions.public-api]
enabled = true
verify_jwt = false

[functions.notification-consumer]
enabled = true
verify_jwt = false

[functions.provider-receipts]
enabled = true
verify_jwt = false
